### ISSUE TITLE
Error running every command

### ISSUE THREAD

**Issue by joruro** [rsanchez/craft-cli#9]
Hey, I installed the package using the composer. Every command is giving me this error. 

`php ./vendor/craft-cli/cli/bin/craft console`

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Console\Exception\RuntimeException' with message 'No arguments expected, got "console".' in /project/vendor/symfony/console/Input/ArgvInput.php:184
Stack trace:
#0 /project/vendor/symfony/console/Input/ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('console')
#1 /project/vendor/craft-cli/cli/src/Console/GlobalArgvInput.php(46): Symfony\Component\Console\Input\ArgvInput->parse()
#2 /project/vendor/symfony/console/Input/Input.php(63): CraftCli\Console\GlobalArgvInput->parse()
#3 /project/vendor/symfony/console/Input/Input.php(49): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 /project/vendor/symfony/console/Inpu in /project/vendor/symfony/console/Input/ArgvInput.php on line 184
```

Do you have a clue of what I can be doing wrong?

**Comment by rsanchez** [comment]
Try running the command like this:

```
php vendor/bin/craft console
```

**Comment by joruro** [comment]
I got the same error

**Comment by rsanchez** [comment]
Can you tell me your symfony/console version found in your composer.lock file? What version of PHP are you running?

**Comment by joruro** [comment]
The version of the symfony/console is `dev-master` (commit `f82f474`) and the PHP version is `5.6`
